# Generated by Django 3.1 on 2020-08-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_page_header',
            field=models.CharField(default='Bloggify!', max_length=255),
        ),
    ]
