# Generated by Django 3.1 on 2020-08-05 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_post_blog_page_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_pub_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_page_header',
            field=models.CharField(max_length=255),
        ),
    ]
