# Generated by Django 3.1 on 2020-08-06 12:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_post_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
